################################################################################
# Joshua C. Fjelstul, Ph.D.
# eums R package
# automatically generated by the codebookr R package
################################################################################

#' Directed dyad-year data on member states
#' 
#' This dataset is a template for directed dyad-year data on member states.
#' There is one observation per directed dyad per year.
#' 
#' @format A data frame with 8 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation.}
#' \item{year}{\code{numeric}. The year.}
#' \item{from_member_state_id}{\code{numeric}. An ID number that uniquely
#' identifies each member state.}
#' \item{from_member_state}{\code{string}. The name of the first member state
#' in the directed dyad. }
#' \item{from_member_state_code}{\code{string}. A two-letter code assigned to
#' each member state by the Commission.}
#' \item{to_member_state_id}{\code{numeric}. An ID number that uniquely
#' identifies each member state.}
#' \item{to_member_state}{\code{string}. The name of the second member state
#' in the directed dyad.}
#' \item{to_member_state_code}{\code{string}. A two-letter code assigned to
#' each member state by the Commission.}
#' }
"member_states_ddy"

################################################################################
# end R script
################################################################################

