################################################################################
# Joshua C. Fjelstul, Ph.D.
# eums R package
# automatically generated by the codebookr R package
################################################################################

#' Cross-sectional time-series template
#' 
#' This dataset is a template for cross-sectional time-series data on member
#' states. There is one observation per member state per year.
#' 
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation.}
#' \item{year}{Numeric. The year.}
#' \item{member_state_id}{Numeric. An ID number that uniquely identifies each
#' member state.}
#' \item{member_state}{String. The name of the member sate.}
#' \item{member_state_code}{String. A two-letter code assigned to each member
#' state by the Commission.}
#' \item{years_as_member}{Numeric. The number of years that the member state
#' has been a member, with the first year of membership coded \code{1}.}
#' }
"member_states_csts"

################################################################################
# end R script
################################################################################

