################################################################################
# Joshua C. Fjelstul, Ph.D.
# eums R package
# automatically generated by the codebookr R package
################################################################################

#' Data on qualified majority voting (QMV) weights
#' 
#' This dataset includes data on qualified majority voting (QMV) weights in
#' the Council of the European Union. The total number of votes allocated
#' across member states and the number of votes allocated to each member state
#' have changed over time. This dataset tracks those changes and calculates
#' the normalized voting weight for each member state for each period.
#' 
#' @format A data frame with 17 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation.}
#' \item{period}{\code{numeric}. An ID number that uniquely identifies each
#' period.}
#' \item{start_date}{\code{date}. The start day of the period in the format
#' \code{YYYY-MM-DD}.}
#' \item{start_year}{\code{numeric}. The start year of the period.}
#' \item{start_month}{\code{numeric}. The start month of the period.}
#' \item{start_day}{\code{numeric}. The start day of the period.}
#' \item{end_date}{\code{date}. The end date of the period in the format
#' \code{YYYY-MM-DD}.}
#' \item{end_year}{\code{numeric}. The end year of the period.}
#' \item{end_month}{\code{numeric}. The end month of the period.}
#' \item{end_day}{\code{numeric}. The end day of the period.}
#' \item{count_member_states}{\code{numeric}. The number of member states.}
#' \item{member_state_id}{\code{numeric}. An ID number that uniquely
#' identifies each member state. }
#' \item{member_state}{\code{string}. The name of the member state.}
#' \item{member_state_code}{\code{string}. A two-letter code assigned to each
#' member state by the Commission.}
#' \item{votes}{\code{numeric}. The number of votes allocated to each member
#' state during the period.}
#' \item{total_votes}{\code{numeric}. The total number of votes allocated
#' across all member states during the period.}
#' \item{normalized_weight}{\code{numeric}. The normalized voting weight of
#' the member state during the period. Calculated as the number of votes
#' allocated to the member state divided by the total number of votes
#' allocated to all member states.}
#' }
"qmv_weights"

################################################################################
# end R script
################################################################################

